name: Flutter CI

on:
  push:
    branches: [ master ]

jobs:
  process:
    name: all process
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v1.3.0
        with:
          java-version: "12.x"

      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@v1.1.1
        with:
          channel: "stable"

      # 下载项目依赖          
      - name: Install dependencies
        run: |
          cd you_wallet
          flutter pub get
          flutter build apk --release
      - name: Release apk
        uses: ncipollo/release-action@v1.5.0
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.GIT_RElEASE_TOKEN }}
